# Generated by Django 5.1 on 2024-08-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarystore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='bnanner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
