# Generated by Django 5.1 on 2024-08-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarystore', '0002_novel_bnanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='bnanner',
            field=models.ImageField(blank=True, default='fallback.webp', upload_to=''),
        ),
    ]
