# Generated by Django 5.1 on 2024-08-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarystore', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
